Repository Hongik-Mentoring-Team/hongyeon-back, pull requests merged in 2025-01, with the labels that each got.

#18 [PR] 이슈 템플릿
  .github/ISSUE_TEMLATE/bug_report.md
  .github/ISSUE_TEMLATE/feature_request.md
  .github/ISSUE_TEMLATE/other_issues.md
Labels: 🔨Setting

#19 [PR] 이슈 템플릿
  .github/ISSUE_TEMLATE/bug_report.md
  .github/ISSUE_TEMLATE/feature_request.md
  .github/ISSUE_TEMLATE/other_issues.md
Labels: 🔨Setting

#20 Update issue templates
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-보고.md
Labels: 🔨Setting

#21 [PR] 브랜치 동기화
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-보고.md
Labels: 🔨Setting

#27 [PR] PR 템플릿 생성
  .github/pull_request_template.md
Labels: 🔨Setting

#29 [PR] x: Issue 및 PR 템플릿 파일 생성
  .github/ISSUE_TEMLATE/bug_report.md
  .github/ISSUE_TEMLATE/feature_request.md
  .github/ISSUE_TEMLATE/other_issues.md
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/pull_request_template.md
Labels: 🔨Setting

#33 [PR] #x: 브랜치 통합
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-보고.md
Labels: 🤞Integration

#34 Feature/#13 게시글 작성수정조회삭제 기본 api 구현
  .gitignore
  build.gradle
  src/main/java/com/hongik/mentor/hongik_mentor/HongikMentorApplication.java
  src/main/java/com/hongik/mentor/hongik_mentor/Initializer/TagInitializer.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/PostController.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/PostCreateDTO.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/PostDTO.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/PostModifyDTO.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/TagDTO.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Comment.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Post.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/PostLike.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/PostTag.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Tag.java
  src/main/java/com/hongik/mentor/hongik_mentor/exception/CustomMentorException.java
  src/main/java/com/hongik/mentor/hongik_mentor/exception/ErrorCode.java
  src/main/java/com/hongik/mentor/hongik_mentor/exception/ErrorResponseEntity.java
  src/main/java/com/hongik/mentor/hongik_mentor/exception/MentoringExceptionHandler.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/PostRepository.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/PostSearchRepository.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/PostSearchRepositoryImpl.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/TagRepository.java
  src/main/java/com/hongik/mentor/hongik_mentor/service/PostService.java
  src/main/java/com/hongik/mentor/hongik_mentor/service/dto/PostLikeDTO.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.yml
  src/test/java/com/hongik/mentor/hongik_mentor/repository/MemberRepositoryTest.java
  src/test/java/com/hongik/mentor/hongik_mentor/service/PostServiceTest.java
Labels: ✨Feature

#41 [PR] Update README.md
  README.md
Labels: 🔨Setting

#49 Feature/#35 팔로워 팔로잉 기능 구현
  src/main/java/com/hongik/mentor/hongik_mentor/controller/FollowController.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/FollowRequestDTO.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Follow.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Member.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Post.java
  src/main/java/com/hongik/mentor/hongik_mentor/exception/ErrorCode.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/FollowRepository.java
  src/main/java/com/hongik/mentor/hongik_mentor/service/MemberService.java
  src/test/java/com/hongik/mentor/hongik_mentor/service/FollowServiceTest.java
Labels: ✨Feature

#45 feat : #44/수강 후기 작성/수정/조회/삭제 기본 API 구현
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/MemberResponseDto.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/ReviewResponseDto.java
  src/main/java/com/hongik/mentor/hongik_mentor/controller/dto/ReviewSaveDto.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Member.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Post.java
  src/main/java/com/hongik/mentor/hongik_mentor/domain/Review.java
  src/main/java/com/hongik/mentor/hongik_mentor/repository/ReviewRepository.java
  src/main/java/com/hongik/mentor/hongik_mentor/service/PostService.java
  src/main/java/com/hongik/mentor/hongik_mentor/service/ReviewService.java
Labels: ✨Feature
